import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { useState } from 'react';
import { Hydrate, QueryClient, QueryClientProvider } from 'react-query';
import Head from 'next/head';
import MainLayout from '@/src/layouts/MainLayout';
import { NextPage } from 'next';
import { AuthProvider } from '@/src/contexts/authContext';
import {useAppToastGetter} from "@/src/hooks/toast";
import AppToast from "@/src/components/atoms/toast/AppToast";

interface MyAppProps extends AppProps {
	Component: NextPage;
}

export default function App(props: MyAppProps) {
	const { Component, pageProps } = props;

	const getLayout = Component.getLayout ?? ((page) => <MainLayout>{page}</MainLayout>);
	const toast = useAppToastGetter();

	const [queryClient] = useState(
		() =>
			new QueryClient({
				defaultOptions: {
					queries: {
						retry: false,
						suspense: true,
					},
				},
			})
	);
	return (
		<>
			<Head>
				<title>Pliper Web</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon/favicon.ico' />
			</Head>
			<QueryClientProvider client={queryClient}>
				<Hydrate state={pageProps.dehydratedState}>
					<AuthProvider>
						{getLayout(<Component {...pageProps} />)}
						<AppToast {...toast} />
					</AuthProvider>
				</Hydrate>
			</QueryClientProvider>
		</>
	);
}
