name: Deploy

on:
  push:
    branches: [ "github-action-test", "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Yarn
        run: npm install -g yarn # Yarn 설치

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Clean Next Dir
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/emotion-web
            rm -rf .next

      - name: Deploy to Lightsail using SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: ".next/"
          target: "/home/ubuntu/apps/pliper-web"

      - name: Deploy to Lightsail using SCP ( Public Path )
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "public"
          target: "/home/ubuntu/apps/pliper-web"


      - name: Restart Next.js service on Lightsail using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/apps/pliper-web
            cp -r .next/standalone ./
            cp -r .next/static ./.next/static
            
            cd /home/ubuntu/apps/pliper-web && sudo pm2 restart server.js
