name: Deploy

on:
  push:
    branches: [ "github-action-test", "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install -g yarn # Yarn 설치

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
#
#      - name: Clean Next Dir
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          port: ${{ secrets.PORT }}
#          key: ${{ secrets.KEY }}
#          script: |
#            cd /home/ubuntu/emotion-web
#            rm -rf .next

      - name: Deploy "Public" to Lightsail
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "public"
          target: "/home/ubuntu/apps/pliper-web"

      - name: Deploy ".Next" to Lightsail (1/2)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "./.next/standalone/*"
          target: "/home/ubuntu/apps/pliper-web"
          strip_components: 2

#      - name: Deploy ".next" to Lightsail (2/2)
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          port: ${{ secrets.PORT }}
#          key: ${{ secrets.KEY }}
#          script: |
#            cd /home/ubuntu/apps/pliper-web
#            cp -r standalone/* ./ && rm -rf standalone

      - name: Deploy ".next/static" to Lightsail
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: ".next/static"
          target: "/home/ubuntu/apps/pliper-web/.next"
          strip_components: 1

      - name: Restart Next.js service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/apps/pliper-web && sudo  pm2 reload server.js
